<?php
$title = 'Add new brewery';
$this->headTitle($title);
?>
<div class="clearfix"></div>
<div style="width:100%;">
<h1><?= $this->escapeHtml($title) ?></h1>
</div>
<div style="width:100%;">
<?php
// This provides a default CSS class and placeholder text for the title element:
$brewery = $form->get('name');
$brewery->setAttribute('class', 'form-control');
$brewery->setAttribute('placeholder', 'Brewery name');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('manage/brewery', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($brewery) ?>
    <?= $this->formElement($brewery) ?>
    <?= $this->formElementErrors()->render($brewery, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>