<?php

$title = 'Edit brewery';
$this->headTitle($title);
?>
<div class="clearfix"></div>
<div style="width:100%;">
<h1><?= $this->escapeHtml($title) ?></h1>
</div>
<div style="width:100%;">
<?php
$brewery = $form->get('name');
$brewery->setAttribute('class', 'form-control');
$brewery->setAttribute('placeholder', 'Brewery name');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('manage/brewery', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($brewery) ?>
    <?= $this->formElement($brewery) ?>
    <?= $this->formElementErrors()->render($brewery, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>