<?php

$title = 'All Breweries';
$this->headTitle($title);
?>
<div style="width:100%;">
    <div class="col-md-5" style="display:inline-block;">
<h1><?= $this->escapeHtml($title) ?></h1>
</div>

    <div class="col-md-7 float-right" style="display:inline-block;vertical-align: middle;margin-top: 15px;">
    <a href="<?= $this->url('manage/brewery', ['action' => 'add']) ?>">Add new brewery</a>
</div>
</div>

<table class="table">
<tr>
    <th>Name</th>
    <th>&nbsp;Action</th>
</tr>
<?php if (empty($breweries) || count($breweries) < 1) { ?>
<tr>
    <td colspan="2">No brewery.</td>
</tr>
<?php } else { ?>
<?php foreach ($breweries as $brewery) : ?>
    <tr>
        <td><?= $this->escapeHtml($brewery->name) ?></td>
        <td>
            <a href="<?= $this->url('manage/brewery', ['action' => 'edit', 'id' => $brewery->id]) ?>">Edit</a>
            <a href="<?= $this->url('manage/brewery', ['action' => 'delete', 'id' => $brewery->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
<?php }  ?>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->breweries,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'manage/brewery']
) ?>