<?php

$title = 'Delete beer category';
$url   = $this->url('category', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<div class="clearfix"></div>
<div style="width:100%;">
<h1><?= $this->escapeHtml($title) ?></h1>
</div>
<div style="width:100%;">
<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($category->name) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $category->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>
</div>