<?php

$title = 'Edit beer style';
$this->headTitle($title);
?>
<div class="clearfix"></div>
<div style="width:100%;">
<h1><?= $this->escapeHtml($title) ?></h1>
</div>
<div style="width:100%;">
<?php
$style = $form->get('name');
$style->setAttribute('class', 'form-control');
$style->setAttribute('placeholder', 'Style name');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('manage/style', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($style) ?>
    <?= $this->formElement($style) ?>
    <?= $this->formElementErrors()->render($style, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>